### ISSUE TITLE
Tests fail with -Duselongdouble

### ISSUE THREAD

**Issue by eserte** [yoheimuta/Linux-GetPidstat#11]
If perl is compiled with -Duselongdouble, then the test suite fails. A sample fail report: http://www.cpantesters.org/cpan/report/446e5d0a-9ce2-11e7-9566-d5529ae40bc1

**Comment by yoheimuta** [comment]
Thank you for sharing a report.
I'm going to fix it up.

**Comment by yoheimuta** [comment]
I fixed it #12.
